# Generated by Django 3.0.7 on 2020-06-13 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('courseType', models.CharField(max_length=40)),
                ('transType', models.CharField(max_length=225)),
                ('days', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('startDate', models.DateField()),
                ('transType', models.CharField(max_length=50)),
                ('courseChosen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=225)),
                ('typeOfQuestion', models.CharField(max_length=25)),
                ('step', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(help_text='Enter an option you want displayed', max_length=255, verbose_name='Option')),
                ('transType', models.CharField(blank=True, max_length=20)),
                ('score', models.IntegerField()),
                ('endpoint', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(help_text='Enter a feature you want displayed', max_length=255, verbose_name='Feature')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.Course')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
