# Generated by Django 3.0.7 on 2020-06-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseType',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
