# Generated by Django 3.0.7 on 2020-07-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200613_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='transType',
            new_name='postCode',
        ),
    ]
