# Generated by Django 3.0.7 on 2020-06-11 23:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('transType', models.CharField(max_length=225)),
                ('days', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('startdate', models.DateField()),
                ('transType', models.CharField(max_length=50)),
                ('coursechosen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(help_text='Enter an option you want displayed', max_length=255, verbose_name='Option')),
                ('score', models.IntegerField()),
                ('endpoint', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=225)),
                ('typeOfQuestion', models.CharField(max_length=25)),
                ('step', models.IntegerField()),
                ('options', models.ManyToManyField(related_name='_question_options_+', to='api.Option')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question', verbose_name='Question'),
        ),
    ]
