# Generated by Django 3.0.7 on 2020-06-11 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='coursechosen',
            new_name='courseChosen',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='startdate',
            new_name='startDate',
        ),
    ]
