# Generated by Django 3.0.7 on 2020-06-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200612_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='features',
        ),
    ]
