# Generated by Django 3.0.7 on 2020-06-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_course_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Question'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(help_text='Enter a feature the user would enjoy by taking the course', max_length=255, verbose_name='Option')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.Course')),
            ],
        ),
    ]
