# Generated by Django 3.0.7 on 2020-06-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200612_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='feature',
            name='desc',
            field=models.CharField(help_text='Enter a feature you want displayed', max_length=255, verbose_name='Feature'),
        ),
    ]
